name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.00
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
